import type { Metadata } from "next";
import "../styles/globals.css";
import { raleway } from "../fonts/font";
import Header from "@/components/layout/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Header/>
        <div className={`mt-[90px] ${raleway.className}`}>
          {children}
        </div>
      </body>
    </html>
  );
}
